import type { NextPage } from 'next';
import Head from 'next/head';

import UserInfoModule from '../components/UserInfoModule/UserInfoModule';
import TokenRow from '../components/TokenRow/TokenRow';
import styles from '../styles/index.module.css';

const ERC20TokenList = ['GRT', 'USDC', 'UNI', 'WBTC', 'ZIL'];

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Buttonwood</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin=""
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main className={styles.main}>
        <div className={styles.dashboard}>
          {typeof window !== 'undefined' &&
          (window as any).ethereum !== 'undefined' ? (
            <>
              <UserInfoModule />
              <div className={styles.table}>
                {ERC20TokenList.map(token => (
                  <TokenRow key={token} token={token} />
                ))}
              </div>
            </>
          ) : (
            <h1>This app requires MetaMask</h1>
          )}
        </div>
      </main>
    </div>
  );
};

export default Home;
