import type { NextPage } from 'next';
import { useState } from 'react';
import { providers, utils } from 'ethers';
import Head from 'next/head';

import TokenRow from '../components/TokenRow/TokenRow';
import styles from '../styles/index.module.css';

const ERC20TokenList = ['USDC', 'UNI', 'WBTC'];

const initWeb3Provider = (): providers.Web3Provider =>
  new providers.Web3Provider((window as any).ethereum);

// TODO: get keys for infura and alchemy

const Home: NextPage = () => {
  const [displayInfo, setDisplayInfo] = useState('');

  const getAccount = async (): Promise<string> => {
    const accounts = await (window as any).ethereum.request({
      method: 'eth_requestAccounts',
    });

    const [account] = accounts;
    return account;
  };

  const getWalletBalance = async (): Promise<string> => {
    const address = await getAccount();

    const provider = initWeb3Provider();

    const balance = await provider.getBalance(address);

    const formattedBalance = utils.formatEther(balance);

    return formattedBalance;
  };

  const showWalletAddress = async () => {
    const address = await getAccount();
    setDisplayInfo(address);
  };

  const showETHBalance = async () => {
    const balance = await getWalletBalance();
    setDisplayInfo(balance);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Buttonwood</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin=""
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400&display=swap"
          rel="stylesheet"
        />
      </Head>

      {typeof window !== 'undefined' &&
        (window as any).ethereum !== 'undefined' && (
          <main className={styles.main}>
            <div className={styles.dashboard}>
              <div className={styles.result}>
                <span className={styles.display}>
                  <p>{displayInfo}</p>
                </span>
              </div>
              <div className={styles.controls}>
                <div className={styles.buttonContainer}>
                  <button onClick={showWalletAddress}>wallet address</button>
                  <button onClick={showETHBalance}>ETH balance</button>
                </div>
                {ERC20TokenList.map(token => (
                  <TokenRow key={token} token={token} />
                ))}
              </div>
            </div>
          </main>
        )}
    </div>
  );
};

export default Home;
